name: gals_app
description: アイドルグループ「GALS」にまつわるアプリ.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 画面遷移
  go_router: 6.2.0

  # 状態管理
  hooks_riverpod: 2.3.6
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  intl: 0.18.0
  cached_network_image: 3.2.3
  carousel_slider: 4.2.1
  modal_bottom_sheet: 2.1.2
  google_fonts: 4.0.3
  json_annotation: 4.8.0
  flutter_hooks: 0.18.6
  url_launcher: 6.1.10
  firebase_core: 2.14.0
  cloud_firestore: 4.8.1
  retrofit: 4.0.1
  dio: 5.0.1
  retrofit_generator: 5.0.0
  flutter_localization: 0.1.10
  table_calendar: 3.0.9
  flutter_html: 3.0.0-alpha.6
  share_plus: 6.3.1
  font_awesome_flutter: 10.4.0
  firebase_crashlytics: 3.3.3
  package_info_plus: 3.1.2
  webview_flutter: 4.2.2
  flutter_launcher_icons: 0.12.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/Android.png"
  image_path_ios: "images/iOS.png"
  adaptive_icon_background: '#6cc6da'
  adaptive_icon_foreground: "images/AdaptiveIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.3.3
  json_serializable: 6.6.1
  riverpod_lint: 1.0.1


flutter:

  uses-material-design: true

  assets:
  - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
