// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wP5viDREu9x3-xiSyo3rD0E5tw9cWhw',
    appId: '1:775948610033:web:dcb9493370e8b68b6bfc50',
    messagingSenderId: '775948610033',
    projectId: 'gals-51236',
    authDomain: 'gals-51236.firebaseapp.com',
    storageBucket: 'gals-51236.appspot.com',
    measurementId: 'G-PDDJP3Z6JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdC3aScpm6CfzUwxYrChGy4oIjkMz-_s',
    appId: '1:775948610033:android:74a44b188be593936bfc50',
    messagingSenderId: '775948610033',
    projectId: 'gals-51236',
    storageBucket: 'gals-51236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECtDIzpurslpCP2ch9WQ-D4UQxHtGz0E',
    appId: '1:775948610033:ios:be5b2e196893db7c6bfc50',
    messagingSenderId: '775948610033',
    projectId: 'gals-51236',
    storageBucket: 'gals-51236.appspot.com',
    iosClientId: '775948610033-t8aiqo532tetm2sl36qdoq6v9ue5dfdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.galsApp',
  );
}
